from setuptools import setup

# Metadata goes in setup.cfg. These are here for GitHub's dependency graph.
setup(
    name="sweetrpg-library-api",
    install_requires=[
        "Authlib",
        "blinker",
        "dnspython<3.0.0",
        "Flask-Caching",
        "Flask-Cors",
        "Flask-DotEnv",
        "Flask-REST-JSONAPI",
        "Flask-Session",
        "Flask<3.0",
        "Flask-Migrate",
        "Flask-MongoEngine",
        "gunicorn",
        "kanka",
        "python-dateutil",
        "python-dotenv",
        "python-editor",
        "python-logstash-async",
        "PyYAML==6.0",
        "redis",
        "requests",
        "sentry-sdk[flask]==1.5.0",
        "analytics-python<2.0",
        "sweetrpg-db",
        "sweetrpg-model-core",
        "sweetrpg-api-core",
        "sweetrpg-library-objects",
        "airtable",
    ],
    extras_require={},
)
