from setuptools import setup

# Metadata goes in setup.cfg. These are here for GitHub's dependency graph.
setup(
    name="sweetrpg-library-api",
    install_requires=[
        "Authlib",
        "blinker",
        "dnspython<2.0.0",
        "Flask-Caching",
        "Flask-Cors",
        "Flask-DotEnv",
        "Flask-REST-JSONAPI",
        "Flask-Session",
        "Flask==2.0.2",
        "Flask-Migrate",
        "Flask-MongoEngine",
        "gunicorn",
        "kanka",
        "python-dateutil",
        "python-dotenv",
        "python-editor",
        "PyYAML==6.0",
        "redis",
        "python-logstash-async",
        "requests",
        "sentry-sdk==1.4.3",
        "analytics-python<2.0",
        "sweetrpg-db @ git+https://github.com/sweetrpg/db.git@develop",
        "sweetrpg-model-core @ git+https://github.com/sweetrpg/model-core.git@develop",
        "sweetrpg-api-core @ git+https://github.com/sweetrpg/api-core.git@develop",
        "sweetrpg-library-objects @ git+https://github.com/sweetrpg/library-objects.git@develop",
    ],
    extras_require={},
)
