# -*- coding: utf-8 -*-
__author__ = "Paul Schifferer <dm@sweetrpg.com>"
"""
constants.py
- Contstants for keys and environment variable names
"""

AUTH0_CLIENT_ID = 'AUTH0_CLIENT_ID'
AUTH0_CLIENT_SECRET = 'AUTH0_CLIENT_SECRET'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_DOMAIN = 'AUTH0_DOMAIN'
AUTH0_AUDIENCE = 'AUTH0_AUDIENCE'

KANKA_CLIENT_ID = 'KANKA_CLIENT_ID'
KANKA_CLIENT_SECRET = 'KANKA_CLIENT_SECRET'
KANKA_CALLBACK_URL = 'KANKA_CALLBACK_URL'
KANKA_DOMAIN = 'KANKA_DOMAIN'
KANKA_AUDIENCE = 'KANKA_AUDIENCE'

SENTRY_DSN = 'SENTRY_DSN'
SENTRY_ENV = 'SENTRY_ENV'

APPLICATION_NAME = "sweetrpg-library-api"
PROFILE_KEY = 'profile'
JWT_PAYLOAD = 'jwt_payload'
CURRENT_USER_ID = 'current_user_id'
