name: CI

concurrency: ci-${{ github.ref }}

on:
    push:
        branches: [develop]
        paths:
            - "src/**"
            - "tests/**"
            - setup.cfg
            - setup.py
            - tox.ini
            - "requirements/**"
            - "docs/**"
    workflow_run:
        workflows: ["Update Requirements"]
        types: [completed]

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        concurrency: ci
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "3.10",
                          os: ubuntu-latest,
                          tox: py310,
                      }
                    # - {
                    #       name: Windows,
                    #       python: "3.10",
                    #       os: windows-latest,
                    #       tox: py310,
                    #   }
                    # - { name: Mac, python: "3.10", os: macos-latest, tox: py310 }
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: update-pip
              run: |
                  pip install -U wheel
                  pip install -U setuptools
                  python -m pip install -U pip
            - name: get-pip-cache-dir
              id: pip-cache
              run: echo "::set-output name=dir::$(pip cache dir)"
            - name: cache-pip
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pip-cache.outputs.dir }}
                  key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('setup.py') }}|${{ hashFiles('requirements/*.txt') }}
            - name: install-utils
              run: pip install tox
            - name: tests
              run: tox -e ${{ matrix.tox }}

    #    docs:
    #        needs: [tests]
    #        runs-on: ubuntu-latest
    #        concurrency: docs
    #        steps:
    #            - uses: actions/checkout@v3
    #            - uses: actions/setup-python@v4
    #              with:
    #                  python-version: "3.10"
    #            - name: install-deps
    #              run: pip install -r requirements/docs.txt
    #            - name: make-docs
    #              run: cd docs && make html
    #            - name: publish-docs
    #              uses: peaceiris/actions-gh-pages@v3
    #              with:
    #                  github_token: ${{ secrets.GITHUB_TOKEN }}
    #                  publish_dir: ./docs/_build/html

    tag:
        needs: [tests]
        runs-on: ubuntu-latest
        concurrency: publish
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: publish
              uses: relekang/python-semantic-release@master
              with:
                  additional_options: "--patch"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  repository_username: __token__
                  repository_password: ${{ secrets.PYPI_TOKEN }}
